### ISSUE TITLE
Could not find class 'net.time4j.android.ApplicationStarter$TimezoneChangedReceiver'

### ISSUE THREAD

**Issue by omidraha** [MenoData/Time4J#717]
Traceback:

`E/dalvikvm: Could not find class 'net.time4j.android.ApplicationStarter$TimezoneChangedReceiver', referenced from method net.time4j.android.ApplicationStarter.registerReceiver`

And:

```
E/AndroidRuntime: FATAL EXCEPTION: main
	java.lang.NoClassDefFoundError: net.time4j.base.ResourceLoader
		at net.time4j.android.ApplicationStarter.prepareAssets(Unknown Source)
		at net.time4j.android.ApplicationStarter.initialize(Unknown Source)
		at org.example.app.MainApp.onCreate(MainApp.java:57)
		at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
		at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:137)
		at android.app.ActivityThread.main(ActivityThread.java:5041)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:511)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
		at dalvik.system.NativeStart.main(Native Method)

```

The `MainApp.java`: 

```
import net.time4j.android.ApplicationStarter;

    @Override
    public void onCreate() {
        super.onCreate();
        ApplicationStarter.initialize(this, true);
...
}
```

The `build.gradle`  file:

```
dependencies {
    testCompile 'junit:junit:4.12'
    compile group: 'net.time4j', name: 'time4j-android', version: '3.37-2017c'
...
 }
```

**Comment by MenoData** [comment]
Strange that your scenario knows the class `ApplicationStarter` but not its static inner class `TimezoneChangedReceiver`. Hm, I am just speculating: Maybe a tool similar to Proguard has mistakenly removed that inner class from the generated APK. Can you please give more informations about your intialization and configuration?

- Do you apply any obfuscating or shrinking tool like Proguard?
- Or do you apply any kind of instrumentation tool?

By the way, I cannot reproduce your problem, not even if I apply Proguard (which is clever enough to see by code analysis that the `TimezoneChangedReceiver` is needed during the initialization).

**Comment by omidraha** [comment]
Here is my full `build.gradle` file:

```
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
//apply plugin: 'io.sentry.android.gradle'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "org.badansaz.app"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        // https://stackoverflow.com/a/37430389/538284
        multiDexEnabled true
    }
    // https://developer.android.com/studio/build/shrink-code.html
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
repositories {
    mavenCentral()
    jcenter()
//    flatDir {
//        dirs 'libs'
//    }
    google()
}

dependencies {
    testCompile 'junit:junit:4.12'
//    debugCompile 'com.github.jonasrottmann.realm-browser:realm-browser:0.0.14'
    compile group: 'net.time4j', name: 'time4j-android', version: '3.37-2017c'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'io.sentry:sentry-android:1.6.1'
    //  compile 'ch.qos.logback:logback-classic:1.1.7'
    //noinspection GradleCompatible
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:leanback-v17:26.1.0'
    compile 'io.realm:android-adapters:2.1.0'
    compile 'com.koushikdutta.ion:ion:2.1.9'
    compile 'com.makeramen:roundedimageview:2.3.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    compile 'com.github.manuelpeinado.multichoiceadapter:multichoiceadapter:3.0.0'
    compile 'com.afollestad.material-dialogs:core:0.9.4.5'
    compile 'ru.egslava:MaskedEditText:1.0.5'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'
    compile 'com.mohamadamin:persianmaterialdatetimepicker:1.2.1'
    compile 'com.firebase:firebase-jobdispatcher:0.7.0'
    compile 'org.greenrobot:eventbus:3.1.0-RC'
//    compile 'com.google.android.gms:play-services-maps:11.6.0'
    compile 'com.schibstedspain.android:leku:3.5.0'
}
```

**Comment by MenoData** [comment]
Okay, I strongly suspect that you have run into a multidex problem. The Time4A-classes should be in the primary dex file (because you use it as entry point to your app). You can read more about this topic when you follow the official Android link:

https://developer.android.com/studio/build/multidex.html#keep

It is mainly the section "Declare classes required in the primary DEX file" and the option "multiDexKeepProguard". If you specify that extra configuration file (like via "multiDexKeepProguard file('multidex-config.pro')") then try to include all Time4A-classes you use in your app. In the simplest case or as first approach, you can include all by using **-syntax but then try to optimize it. For example, you might include all SPX-filex you need (a start for experiments might also be the files mentioned in https://github.com/MenoData/Time4A/blob/master/time4j-android/consumer-proguard-rules.pro).

Personally I have no experience with multidex-apps but hope that these lines give you a hint. Good luck!

**Comment by omidraha** [comment]
Temporarily fixed by:

`build.gradle`

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            multiDexKeepProguard file('proguard-rules.pro')
            debuggable true
        }
    }

`proguard-rules.pro` 

```
-keep class org.example.** {*;}
-keep class net.time4j.** { public *; }
-keep class io.realm.** {*;}
-keep class android.support.** {*;}
-keep class com.makeramen.** {*;}
-keep class com.nineoldandroids.** {*;}
-keep class com.squareup.picasso.** {*;}
-keep class com.daimajia.slider.** {*;}
-keep class com.firebase.** {*;}
-keep class de.jonasrottmann.realmbrowser.** {*;}

```

Thanks,

**Comment by MenoData** [comment]
Happy coding!
