### ISSUE TITLE
Infinite Recursion (StackOverflowError) when converting IntervalCollection to Json

### ISSUE THREAD

**Issue by charlesxucheng** [MenoData/Time4J#745]
Hi there. 

I am doing JSON serialization for IntervalCollection and hit the following error:

System.out.println(JsonUtil.toJson(IntervalCollection.onDateAxis().plus(DateInterval.between(LocalDate.of(2015, 1, 1), LocalDate.of(2015, 1, 2)))))

My code is in Scala but using Jackson to do JSON processing.

Infinite recursion (StackOverflowError) (through reference chain: net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]->java.util.Collections$UnmodifiableSet[11]->net.time4j.DateElement["defaultMinimum"]->net.time4j.PlainDate["registeredElements"]-> ...
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:734)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)

JsonUtil is as follows (modified from here https://coderwall.com/p/o--apg/easy-json-un-marshalling-in-scala-with-jackson):
```
import com.fasterxml.jackson.databind.{DeserializationFeature, ObjectMapper}
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule

object JsonUtil {
  val mapper = new ObjectMapper() with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)
    .registerModule(new ParameterNamesModule())
    .registerModule(new Jdk8Module())
    .registerModule(new JavaTimeModule());
  mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

  def toJson(value: Map[Symbol, Any]): String = {
    toJson(value map { case (k,v) => k.name -> v})
  }

  def toJson(value: Any): String = {
    mapper.writeValueAsString(value)
  }

  def toMap[V](json:String)(implicit m: Manifest[V]) = fromJson[Map[String,V]](json)

  def fromJson[T](json: String)(implicit m : Manifest[T]): T = {
    mapper.readValue[T](json)
  }
}
```

**Comment by MenoData** [comment]
I am not a specialist for JSon but what I can say is that the types in the range-package are well tested for serialization. For example see [this test](https://github.com/MenoData/Time4J/blob/99fb04d43bc2c3886156d8e2b8a14e0f479bfdcf/range/src/test/java/net/time4j/range/SerializationTest.java#L105) which uses the standard Java serialization.

It seems you need any kind of specialized converter for JSON to make JSON-serialization to work.

**Comment by MenoData** [comment]
Have you now solved this issue? I see your other issue https://github.com/json4s/json4s/issues/502 where you say that you have written a JSON-converter/adapter. Meanwhile I think I cannot do much here but solving the future task to create an extra module for JSOn containing some standard converters (see linked issue #746).

**Comment by charlesxucheng** [comment]
Hi. Thanks for asking. I did not get any response for my Json4s issue, so I have switched to Circe. It worked fine. Below is the code for Circe for your info
```
  implicit val encoderDateInterval: Encoder[DateInterval] = Encoder.instance { dateInterval =>
    val startDate = dateInterval.getStart.getTemporal
    val endDate = if (dateInterval.getEnd.isInfinite) PlainDate.from(MAGIC_DATE) else dateInterval.getEnd.getTemporal
    Json.arr(
      Json.fromInt(startDate.getYear),
      Json.fromInt(startDate.getMonth),
      Json.fromInt(startDate.getDayOfMonth),
      Json.fromInt(endDate.getYear),
      Json.fromInt(endDate.getMonth),
      Json.fromInt(endDate.getDayOfMonth)
    )
  }

  implicit val decoderDateInterval: Decoder[DateInterval] = Decoder.instance { c =>
    c.focus.flatMap(_.asArray) match {
      case Some(sy +: sm +: sd +: ey +: em +: ed +: rest) =>
        for {
          startYear <- sy.as[Int]
          startMonth <- sm.as[Int]
          startDay <- sd.as[Int]
          endYear <- ey.as[Int]
          endMonth <- em.as[Int]
          endDay <- ed.as[Int]
        } yield {
          val startDate = LocalDate.of(startYear.intValue(), startMonth.intValue(), startDay.intValue())
          val endDate = LocalDate.of(endYear.intValue(), endMonth.intValue(), endDay.intValue())
          if (DateHelper.isMagicDate(endDate)) DateInterval.since(startDate)
          else DateInterval.between(startDate, endDate)
        }
    }
  }
```

**Comment by MenoData** [comment]
Thank you very much for the feedback. It is surely useful how to apply JSON-serialization in scala context. So I can now close this issue. Just a small notice about your code though: You can probably replace `LocalDate` by `PlainDate` in order to save some minor conversion costs.
