### ISSUE TITLE
UnsupportedOperationException in TransitionResolver

### ISSUE THREAD

**Issue by ElectronicWizard** [MenoData/Time4J#804]
I was trying to use the GapResolver, and have even resorted to copy/pasting a solution you yourself posted on StackOverflow. However, it keeps throwing the error below:
`java.lang.UnsupportedOperationException: net.time4j.tz.TransitionResolver: [gap=NEXT_VALID_TIME,overlap=EARLIER_OFFSET]
at net.time4j.tz.PlatformTimezone.with(PlatformTimezone.java:446)
at com.test.Main.main(Main.java:275)`

**Comment by MenoData** [comment]
Sorry for the late answer. I don't know how you have got your timezone-object but this behaviour is expected for a timezone without public transition history (as given by a `PlatformTimezone` which is just a wrapper around a `java.util.TimeZone`). This is also [documented](http://time4j.net/javadoc-en/net/time4j/tz/Timezone.html#with-net.time4j.tz.TransitionStrategy-).

One way to reproduce your problem is:

```
Timezone.of("java.util.TimeZone~Europe/Berlin") // enforces the usage of the zone wrapper
    .with(GapResolver.NEXT_VALID_TIME.and(OverlapResolver.EARLIER_OFFSET));
```

However, two details are more or less subject to further consideration.

- Using `Timezone.ofPlatform()` does not reproduce this issue which is in contradiction to the spec.
- We could also investigate the alternative to use a `Timezone`-object delegating to `ZoneId.systemDefault()` on Java-8 or later because latter one has a public transition history.
