### ISSUE TITLE
Attempt to invoke java.util.Set.contains on a null object reference

### ISSUE THREAD

**Issue by mojtaba-yekta** [MenoData/Time4J#894]
Hi, I have received an exception as below in Crashlytics:

**TimeAxis.java**
_net.time4j.engine.TimeAxis$Builder.appendElement_

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at net.time4j.tz.model.DaylightSavingRule.<init>(DaylightSavingRule.java)
       at net.time4j.tz.model.GregorianTimezoneRule.<init>(GregorianTimezoneRule.java)
       at net.time4j.tz.model.FixedDayPattern.<init>(FixedDayPattern.java)
       at net.time4j.tz.model.SPX.readCompositeTransitionModel(SPX.java)
       at net.time4j.tz.model.SPX.readOffset(SPX.java)
       at net.time4j.tz.model.SPX.readCompositeTransitionModel(SPX.java)
       at net.time4j.tz.model.SPX.readExternal(SPX.java)
       at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1823)
       at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
       at net.time4j.tz.spi.TimezoneRepositoryProviderSPI.checkMagicLabel(TimezoneRepositoryProviderSPI.java)
       at net.time4j.tz.Timezone.access$1600(Timezone.java)
       at net.time4j.tz.Timezone.getDefaultTZ(Timezone.java)
       at net.time4j.tz.Timezone.<clinit>(Timezone.java)
       at net.time4j.android.ApplicationStarter$1.run(ApplicationStarter.java)
       at java.lang.Thread.run(Thread.java:818)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.contains(java.lang.Object)' on a null object reference
       at net.time4j.engine.TimeAxis$Builder.appendElement(TimeAxis.java)
       at net.time4j.PlainTime.access$2100(PlainTime.java)
       at net.time4j.PlainTime.<clinit>(PlainTime.java)
       at net.time4j.tz.model.DaylightSavingRule.<init>(DaylightSavingRule.java)
       at net.time4j.tz.model.GregorianTimezoneRule.<init>(GregorianTimezoneRule.java)
       at net.time4j.tz.model.FixedDayPattern.<init>(FixedDayPattern.java)
       at net.time4j.tz.model.SPX.readCompositeTransitionModel(SPX.java)
       at net.time4j.tz.model.SPX.readOffset(SPX.java)
       at net.time4j.tz.model.SPX.readCompositeTransitionModel(SPX.java)
       at net.time4j.tz.model.SPX.readExternal(SPX.java)
       at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1823)
       at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
       at net.time4j.tz.spi.TimezoneRepositoryProviderSPI.checkMagicLabel(TimezoneRepositoryProviderSPI.java)
       at net.time4j.tz.Timezone.access$1600(Timezone.java)
       at net.time4j.tz.Timezone.getDefaultTZ(Timezone.java)
       at net.time4j.tz.Timezone.<clinit>(Timezone.java)
       at net.time4j.android.ApplicationStarter$1.run(ApplicationStarter.java)
       at java.lang.Thread.run(Thread.java:818)
```

**Time4A version:** 4.4.4-2019c

**Device:** samsung

**Model:** Galaxy Grand Prime

**android Version:** 5.0.2

can you please help me handle this Error?

**Comment by MenoData** [comment]
I don't really understand the stack trace because the method `appendElement(...)` does not handle `set.contains(...)` but the whole thing looks like an initialization problem in your app. 

Can you please describe how do you exactly start your app or call the `ApplicationStarter` ? On your own self-constructed thread or as recommended via the static `initialization(...)`-methods?

One thing you could try is to call 
```
ApplicationStarter.initialize(context, false);
Log.i("TIME4A", "Starting Time4A at " + SystemClock.currentMoment());
Executors.defaultThreadFactory().newThread(
                new Runnable() {
                    @Override
                    public void run() {
                        int offset =
                            TimeZone.getDefault().getOffset(System.currentTimeMillis()) / 1000;
                        TZID tzid = ZonalOffset.ofTotalSeconds(offset);
                        Locale sysloc = Locale.getDefault();
                        DisplayMode style = DisplayMode.FULL;
                        try {
                            Moment moment = SystemClock.currentMoment();
                            tzid = Timezone.ofSystem().getID();
                            String currentTime =
                                ChronoFormatter.ofMomentStyle(
                                    style,
                                    style,
                                    sysloc,
                                    tzid
                                ).format(moment);
                            Log.i("TIME4A", currentTime);
                        } catch (Throwable thr) {
                            Log.e(
                                "TIME4A",
                                "Error on prefetch thread with: time zone="
                                        + tzid.canonical()
                                        + ", locale=" + sysloc + "!",
                                thr);
                            throw new IllegalStateException(thr); // rethrow for Google Play Store etc.
                        }
                    }
                }
).start();
```

Please be so kind to report to me if this successful for you. Anyway, I have already committed some minor changes in the initialization code in the hope to make it more robust.

**Comment by mojtaba-yekta** [comment]
In my Application class I had written this:

`ApplicationStarter.initialize(this, true);`

Now I changed my initialization like what you described, Thanks for your help.

One of my users got that error, I couldn't reproduce the error. Now I changed the code and everything look like fine.

Thanks Again!
