### ISSUE TITLE
NullPointerException on deserializing SolarTime

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#901]
For example, if we run the following program **(using Time4J version 5.5)**:
```java
import net.time4j.calendar.astro.SolarTime;

import java.io.*;

@SuppressWarnings("SameParameterValue")
public class SolarTimeTest {
    public static void main(String[] args) throws IOException, ClassNotFoundException {
        SolarTime solarTime = SolarTime.ofMecca();
        System.out.println(solarTime);
        byte[] bytes = serialize(solarTime);
        SolarTime solarTime2 = deserialize(bytes, SolarTime.class);
        System.out.println(solarTime2);
    }

    private static <T extends Serializable> byte[] serialize(T obj)
            throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(baos);
        oos.writeObject(obj);
        oos.close();
        return baos.toByteArray();
    }

    private static <T extends Serializable> T deserialize(byte[] b, Class<T> clazz)
            throws IOException, ClassNotFoundException {
        ByteArrayInputStream bais = new ByteArrayInputStream(b);
        ObjectInputStream ois = new ObjectInputStream(bais);
        Object o = ois.readObject();
        return clazz.cast(o);
    }
}
```
we get the following output:
```
SolarTime[latitude=21.42256111111111,longitude=39.82612777777778,altitude=298,calculator=TIME4J]
Exception in thread "main" java.lang.NullPointerException
	at net.time4j.calendar.astro.SolarTime.check(SolarTime.java:1194)
	at net.time4j.calendar.astro.SolarTime.readObject(SolarTime.java:1245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1185)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2234)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at SolarTimeTest.deserialize(SolarTimeTest.java:28)
	at SolarTimeTest.main(SolarTimeTest.java:11)
```
The exception occurred in the execution of the following statement:
```java
Object o = ois.readObject();
```

**Comment by MenoData** [comment]
Thanks for reporting. The problem affects both the classes `SolarTime` and `LunarTime`. The same fix was also done for Time4A.

**Comment by iamcalendar** [comment]
Thanks for your attention. I need a bugfix release in Time4A as soon as possible.

**Comment by MenoData** [comment]
Now `v4.5.1-2020a` has been released. :-)
