### ISSUE TITLE
OSGi: PrettyTime class not working

### ISSUE THREAD

**Issue by kapil-gahlawat** [MenoData/Time4J#916]
I have java 8 version (1.8.0_202-b08) and using **time4j-base (5.6)** but not able to localize the duration in my **OSGi** bundle.

**code**:
       Duration<ClockUnit> dur = Duration.of(337540, ClockUnit.SECONDS).with(Duration.STD_CLOCK_PERIOD);
        String s2 = PrettyTime.of(Locale.FRANCE).print(dur, TextWidth.WIDE);

**Exception**:
Caused by: java.lang.ExceptionInInitializerError: null
	at net.time4j.base.ResourceLoader$InternalServices.\<clinit\>(ResourceLoader.java:496)
	at net.time4j.base.ResourceLoader$StdResourceLoader.services(ResourceLoader.java:467)
	at net.time4j.PrettyTime.\<clinit\>(PrettyTime.java:95)
...
...
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.sling.models.impl.ModelAdapterFactory.invokePostConstruct(ModelAdapterFactory.java:972)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:772)
	... 267 common frames omitted
Caused by: java.lang.IllegalStateException: Stream handler unavailable due to: null
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.openConnection(URLHandlersStreamHandlerProxy.java:311)
	at java.net.URL.openConnection(URL.java:979)
	at net.time4j.base.ResourceLoader$StdResourceLoader.load(ResourceLoader.java:429)
	at net.time4j.format.internal.PropertyBundle.newBundle(PropertyBundle.java:402)
	at net.time4j.format.internal.PropertyBundle.load(PropertyBundle.java:178)
	at net.time4j.format.internal.IsoTextProviderSPI.\<clinit\>(IsoTextProviderSPI.java:59)
	... 281 common frames omitted

**Comment by kapil-gahlawat** [comment]
Tried using  **TZDATA.init();** before the 1st line of code.

Exception in this case is:

Caused by: java.lang.ExceptionInInitializerError: null
	at net.time4j.tz.repo.TimezoneRepositoryProviderSPI.<clinit>(TimezoneRepositoryProviderSPI.java)
	at net.time4j.tz.repo.TZDATA.init(TZDATA.java)
         .......
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.sling.models.impl.ModelAdapterFactory.invokePostConstruct(ModelAdapterFactory.java:972)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:772)
	... 267 common frames omitted
Caused by: java.lang.IllegalStateException: Stream handler unavailable due to: null
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.openConnection(URLHandlersStreamHandlerProxy.java:311)
	at java.net.URL.openConnection(URL.java:979)
	at net.time4j.base.ResourceLoader$StdResourceLoader.load(ResourceLoader.java:429)
	at net.time4j.tz.spi.ZoneNameProviderSPI.loadTerritories(ZoneNameProviderSPI.java:235)
	at net.time4j.tz.spi.ZoneNameProviderSPI.<clinit>(ZoneNameProviderSPI.java:86)
	... 280 common frames omitted

**Comment by kapil-gahlawat** [comment]
Tried installing time4j-base as a separate bundle, got NoClassDefFoundError when tried to use PrettyTime:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.time4j.PrettyTime
	....
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.sling.models.impl.ModelAdapterFactory.invokePostConstruct(ModelAdapterFactory.java:972)
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:772)
	... 267 common frames omitted


**Note: My code compiles and all test cases are executed perfectly. This Issue is only at runtime.**

**Comment by MenoData** [comment]
Sorry for late reply.

First I advise you to start your app or process with the system property `-Dnet.time4j.base.useClassloaderOnly=true`, see also the [documentation](http://time4j.net/javadoc-en/net/time4j/base/ResourceLoader.html#USE_OF_CLASSLOADER_ONLY).

I believe that this will help because the very same classloader which is capable of loading the class `PropertyBundle` should also be capable of loading the text resources which are located in the same jar-file. Although I am not an expert for OSGi this assumption should also hold in that environment.

About the exception you observed I am wondering because the method `url.openConnection()` is not documented to throw an `IllegalStateException` but to throw an `IOException` so I think this is also a bug in Apache Felix. Anyway, I have submitted a tiny change in favor of more defensive programming against such unexpected exceptions.

I would be very grateful to receive your feedback for suggested setting of system property.

**Comment by kapil-gahlawat** [comment]
Sorry, could not test over the weekend. Tested today and it is working fine after adding the system property you mentioned.

Thanks for your help.
