### ISSUE TITLE
ZonalOffset atLongitude does not work for Auckland

### ISSUE THREAD

**Issue by stevedes77** [MenoData/Time4J#966]
Version: 5.9

To reproduce

```kotlin
fun main() {
    ZonalOffset.atLongitude(BigDecimal("174.74"))
}
```

Expected: Call works and returns response

Actual:
```
Exception in thread "main" java.lang.IllegalArgumentException: Total seconds out of range while fraction is non-zero: 41937
	at net.time4j.tz.ZonalOffset.<init>(ZonalOffset.java:116)
	at net.time4j.tz.ZonalOffset.atLongitude(ZonalOffset.java:226)
	at *****.SolarTestKt.main(SolarTest.kt:33)
	at *****.SolarTestKt.main(SolarTest.kt)
```

**Comment by MenoData** [comment]
Thanks for pointing out this error.
